config/routes.rb
Direito::Application.routes.draw do

  resources :simulacoes, :only => [:show] do 
    post 'upload_peticao', :on => :member
    post 'upload_provas', :on => :member
  end

  resources :grupos do
    get 'participar', :on => :member
    resources :turmas
    resources :casos
    resources :propostas
  end

  get 'grupos/:id/aprovar/:user_id',  to: 'grupos#aprovar',   as: 'aprovar_participacao'
  get 'grupos/:id/reprovar/:user_id', to: 'grupos#reprovar',  as: 'reprovar_participacao'

  devise_for :users

  root :to => 'grupos#index'

end

app/models/turma.rb
class Turma < ActiveRecord::Base
  attr_accessible :nome
  belongs_to :grupo
  
  has_and_belongs_to_many :alunos, :class_name => "User", :join_table => :alunos_turmas
  has_many :simulacoes
  
  def add_aluno(aluno)
    alunos << aluno
  end
  
end

app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  # GET /turmas
  # GET /turmas.json
  def index
    @grupo = Grupo.find(params[:grupo_id])
    @turmas = @grupo.turmas

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @turmas }
    end
  end

  # GET /turmas/1
  # GET /turmas/1.json
  def show
    @grupo = Grupo.find(params[:grupo_id])
    @turma = Turma.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @turma }
    end
  end

  # GET /turmas/new
  # GET /turmas/new.json
  def new
    @grupo = Grupo.find(params[:grupo_id])
    #segurança
    @turma = @grupo.turmas.build
    

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @turma }
    end
  end

  # GET /turmas/1/edit
  def edit
    @grupo = Grupo.find(params[:grupo_id])
    @turma = Turma.find(params[:id])
  end

  # POST /turmas
  # POST /turmas.json
  def create
    @grupo = Grupo.find(params[:grupo_id])
    @turma = @grupo.turmas.build(params[:turma])
    
    
    respond_to do |format|
      if @turma.save
        format.html { redirect_to [@grupo,@turma], notice: 'Turma foi criado com sucesso.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /turmas/1
  # PUT /turmas/1.json
  def update
    @turma = Turma.find(params[:id])

    respond_to do |format|
      if @turma.update_attributes(params[:turma])
        format.html { redirect_to @turma, notice: 'Turma was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turmas/1
  # DELETE /turmas/1.json
  def destroy
    @grupo = Grupo.find(params[:grupo_id])
    @turma = Turma.find(params[:id])
    @turma.destroy

    respond_to do |format|
      format.html { redirect_to grupo_turmas_path(@grupo) }
      
    end
  end
end

app/helpers/turmas_helper.rb
module TurmasHelper
end

app/views/turmas/_form.html.haml
= form_for ([@grupo, @turma]) do |f|
  -if @turma.errors.any?
    #error_explanation
      %h2= "#{pluralize(@turma.errors.count, "error")} prohibited this turma from being saved:"
      %ul
        - @turma.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nome
    = f.text_field :nome
  .actions
    = f.submit (t('Save'))

app/views/turmas/edit.html.haml
%h1 Editing turma

= render 'form'

= link_to 'Show', @turma
\|
= link_to 'Back', turmas_path

app/views/turmas/index.html.haml
%h1 Listing turmas

%table
  %tr
    %th Nome
    %th
    %th
    %th

  - @turmas.each do |turma|
    %tr
      %td= turma.nome
      %td= link_to t('Show'), grupo_turma_path(@grupo, turma)
      -if can? :manage_participacao, @grupo
        %td= link_to t('Edit'), edit_grupo_turma_path(@grupo, turma)
        %td= link_to t('Destroy'), grupo_turma_path(@grupo, turma), :confirm => 'Are you sure?', :method => :delete, :id => "excluir-grupo-turma-#{@grupo.id.to_s}-#{turma.id.to_s}"

%br

-if can? :manage_participacao, @grupo
  =link_to 'Criar Turma',   new_grupo_turma_path(@grupo.id), :id =>  "criar-turma", :method => :get, :title => 'Criar'
\|
=link_to t('Back'), grupo_path(@grupo)

app/views/turmas/new.html.haml
%h1 
  =t('direito.novaturma')

= render 'form'

= link_to t('Back'), grupo_turmas_path(@grupo)

app/views/turmas/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @turma.nome

= link_to t('Edit'), edit_grupo_turma_path(@grupo, @turma)
\|
= link_to t('Back'), grupo_turmas_path(@grupo)