config/routes.rb
Direito::Application.routes.draw do

  resources :simulacoes, :only => [:show] do 
    post 'upload_peticao', :on => :member
    post 'upload_provas', :on => :member
  end

  resources :grupos do
    get 'participar', :on => :member
    resources :turmas
    resources :casos
    resources :propostas
  end

  get 'grupos/:id/aprovar/:user_id',  to: 'grupos#aprovar',   as: 'aprovar_participacao'
  get 'grupos/:id/reprovar/:user_id', to: 'grupos#reprovar',  as: 'reprovar_participacao'

  devise_for :users

  root :to => 'grupos#index'

end

app/models/grupo.rb
class Grupo < ActiveRecord::Base
  resourcify
  attr_accessible :nome
  has_and_belongs_to_many :participacoes_pendentes, :class_name => "User", :join_table => :grupos_participacoes_pendentes
  has_many :turmas
  has_many :propostas
   
  def add_solicitacao_participacao(user)
    if (not participacoes_pendentes.exists?(user))     
       participacoes_pendentes<<user
    end
  end
 
  def aprovar_participacao(user)
    if (!user.has_role? :member, self)     
      user.add_role :member, self
      self.participacoes_pendentes.delete(user)
    end
  end

  def reprovar_participacao(user)
    self.participacoes_pendentes.delete(user) if self.participacoes_pendentes.exists?(user) 
  end
 
 
end

app/controllers/grupos_controller.rb
class GruposController < ApplicationController
  
  before_filter :authenticate_user!, :except => [:index]

  
  # GET /grupos
  # GET /grupos.json
  def index
    @grupos = Grupo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @grupos }
    end
  end

  # GET /grupos/1
  # GET /grupos/1.json
  def show
    @grupo = Grupo.find(params[:id])
    authorize! :show, @grupo

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @grupo }
    end
  end

  # GET /grupos/new
  # GET /grupos/new.json
  def new
    @grupo = Grupo.new
    authorize! :create, @grupo

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @grupo }
    end
  end

  # GET /grupos/1/edit
  def edit
    @grupo = Grupo.find(params[:id])
    authorize! :edit, @grupo
  end

  # POST /grupos
  # POST /grupos.json
  def create
    @grupo = Grupo.new(params[:grupo])
    authorize! :create, @grupo

    respond_to do |format|
      if @grupo.save
        current_user.add_role :owner, @grupo
        
        format.html { redirect_to grupo_path(@grupo), notice: 'Grupo was successfully created.' }
        format.json { render json: @grupo, status: :created, location: @grupo }
      else
        format.html { render action: "new" }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /grupos/1
  # PUT /grupos/1.json
  def update
    @grupo = Grupo.find(params[:id])
    authorize! :edit, @grupo

    respond_to do |format|
      if @grupo.update_attributes(params[:grupo])
        format.html { redirect_to @grupo, notice: 'Grupo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grupos/1
  # DELETE /grupos/1.json
  def destroy
    @grupo = Grupo.find(params[:id])
    authorize! :destroy, @grupo
    
    @grupo.destroy

    respond_to do |format|
      format.html { redirect_to grupos_url }
      format.json { head :no_content }
    end
  end
  
  def participar
    #solicitar_participacao
    @grupo = Grupo.find(params[:id])
    authorize! :solicitar_participacao, @grupo
    
    @grupo.add_solicitacao_participacao(current_user)

    respond_to do |format|
      
      format.html { redirect_to grupos_url, notice: t('participacao.pedido.enviado') }
      format.json { head :no_content }
    end
    
  end
  
  def aprovar
    @grupo = Grupo.find(params[:id])
    authorize! :manage_participacao, @grupo
    @user = User.find(params[:user_id])
    
    @grupo.aprovar_participacao(@user)

    respond_to do |format|      
      format.html { redirect_to @grupo, notice: t('participacao.aprovada') }
      format.json { head :no_content }
    end
    
  end
  
  def reprovar
    @grupo = Grupo.find(params[:id])
    authorize! :manage_participacao, @grupo
    @user = User.find(params[:user_id])
    
    @grupo.reprovar_participacao(@user)

    respond_to do |format|      
      format.html { redirect_to @grupo, notice: t('participacao.reprovada') }
      format.json { head :no_content }
    end
    
  end
  
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/views/grupos/_form.html.haml
= form_for @grupo do |f|
  -if @grupo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@grupo.errors.count, "error")} prohibited this grupo from being saved:"
      %ul
        - @grupo.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nome
    = f.text_field :nome
  .actions
    = f.submit t('Save')

app/views/grupos/edit.html.haml
%h1 Editing grupo

= render 'form'

= link_to 'Show', @grupo
\|
= link_to 'Back', grupos_path

app/views/grupos/index.html.haml
%h1 Listing grupos

%table
  %tr
    %th Nome
    %th Dono
    %th
    %th
    %th

  - @grupos.each do |grupo|
    %tr
      %td= grupo.nome      
      
      %td= link_to 'Participar', participar_grupo_path(grupo), :id => 'participar-grupo-'+grupo.id.to_s
      %td= link_to 'Show', grupo
      %td= link_to 'Edit', edit_grupo_path(grupo)
      %td= link_to 'Destroy', grupo, :confirm => 'Are you sure?', :method => :delete
      %td= link_to image_tag("excluir.png") , grupo, confirm: 'Você tem certeza que deseja excluir?', method: :delete, :id => 'excluir-grupo-'+grupo.id.to_s, :title => 'Excluir'

%br

= link_to 'Criar Grupo', new_grupo_path

app/views/grupos/new.html.haml
%h1 New grupo

= render 'form'

= link_to 'Back', grupos_path

app/views/grupos/show.html.haml
%p#notice= notice


-if !@grupo.participacoes_pendentes.empty? and can? :manage_participacao, @grupo
  %p.pedidos 'Pedidos de participatção pendentes'
  - @grupo.participacoes_pendentes.each do |user|
    %p
      = user.email 
      = user.id
      = @grupo.id
      = "aprovar-#{user.email}"
      = "reprovar-#{user.email}"
      = link_to image_tag("aprovar.png"),   aprovar_participacao_path(@grupo.id, user.id), :id =>  "aprovar-participacao-#{@grupo.id.to_s}-#{user.id.to_s}", :method => :get, :title => 'Aprovar'
      = link_to image_tag("reprovar.png"), reprovar_participacao_path(@grupo.id, user.id), :id => "reprovar-participacao-#{@grupo.id.to_s}-#{user.id.to_s}", :method => :get, :title => 'Reprovar'


-if can? :manage_turmas, @grupo
  %p
    = link_to 'Criar Turma',   new_grupo_turma_path(@grupo.id), :id =>  "criar-turma", :method => :get, :title => 'Criar'

%p
  %b Nome:
  = @grupo.nome


= link_to t('Propostas'), grupo_propostas_path(@grupo)
\|
= link_to t('Edit'), edit_grupo_path(@grupo)
\|
= link_to t('Back'), grupos_path