config/routes.rb
Direito::Application.routes.draw do

  resources :simulacoes, :only => [:show] do 
    post 'upload_peticao', :on => :member
    post 'upload_provas', :on => :member
  end

  resources :grupos do
    get 'participar', :on => :member
    resources :turmas
    resources :casos
    resources :propostas
  end

  get 'grupos/:id/aprovar/:user_id',  to: 'grupos#aprovar',   as: 'aprovar_participacao'
  get 'grupos/:id/reprovar/:user_id', to: 'grupos#reprovar',  as: 'reprovar_participacao'

  devise_for :users

  root :to => 'grupos#index'

end

app/models/caso.rb
class Caso < ActiveRecord::Base
  resourcify
  attr_accessible :nome, :assunto, :descricao, :estado
  mount_uploader :peticao, PeticaoUploader
  mount_uploader :provas, ProvasUploader

  belongs_to :simulacao

  
  ESTADO = {:nao_iniciado =>0, :aguardando_peticao => 1, :exame_preliminar=>2}
  
  
end

app/controllers/casos_controller.rb
class CasosController < ApplicationController
  # GET /casos
  # GET /casos.json
  def index
    @grupo = Grupo.find(params[:grupo_id])
    @casos = @grupo.casos

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @casos }
    end
  end

  # GET /casos/1
  # GET /casos/1.json
  def show
    @grupo = Grupo.find(params[:grupo_id])
    @caso = Caso.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @caso }
    end
  end

  # GET /casos/new
  # GET /casos/new.json
  def new
    @grupo = Grupo.find(params[:grupo_id])
    @caso = @grupo.casos.build
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @caso }
    end
  end

  # GET /casos/1/edit
  def edit
    @grupo = Grupo.find(params[:grupo_id])
    @caso = Caso.find(params[:id])
  end

  # POST /casos
  # POST /casos.json
  def create
    @grupo = Grupo.find(params[:grupo_id])
    @caso = @grupo.casos.build(params[:caso])

    respond_to do |format|
      if @caso.save
        current_user.add_role :relator, @caso
        format.html { redirect_to [@grupo,@caso], notice: 'Caso foi criado com sucesso.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /casos/1
  # PUT /casos/1.json
  def update
    @grupo = Grupo.find(params[:grupo_id])
    @caso = Caso.find(params[:id])

    respond_to do |format|
      if @caso.update_attributes(params[:caso])
        format.html { redirect_to [@grupo, @caso], notice: 'Caso foi atualizado com sucesso.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /casos/1
  # DELETE /casos/1.json
  def destroy
    @grupo = Grupo.find(params[:grupo_id])
    @caso = Caso.find(params[:id])
    @caso.destroy

    respond_to do |format|
      format.html { redirect_to grupo_casos_path(@grupo) }
    end
  end
end

app/helpers/casos_helper.rb
module CasosHelper
end

app/views/casos/_form.html.haml
= form_for ([@grupo, @caso]) do |f|
  -if @caso.errors.any?
    #error_explanation
      %h2= "#{pluralize(@caso.errors.count, "error")} prohibited this caso from being saved:"
      %ul
        - @caso.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nome
    = f.text_field :nome
  .field
    = f.label :assunto
    = f.text_field :assunto
  .field
    = f.label :descricao
    = f.text_area :descricao
  .actions
    = f.submit t('Save')

app/views/casos/edit.html.haml
%h1 Editing caso

= render 'form'

= link_to t('Show'), [@grupo, @caso]
\|
= link_to t('Back'), grupo_casos_path(@grupo)

app/views/casos/index.html.haml
%h1 Listing casos

%table
  %tr
    %th Nome
    %th Assunto
    %th Descricao
    %th
    %th
    %th

  - @casos.each do |caso|
    %tr
      %td= caso.nome
      %td= caso.assunto
      %td= caso.descricao
      %td= link_to t('Show'), grupo_caso_path(@grupo, caso)
      %td= link_to t('Edit'), edit_grupo_caso_path(@grupo, caso), :id => "editar-caso-#{caso.id.to_s}"
      %td= link_to t('Destroy'), grupo_caso_path(@grupo, caso), :confirm => 'Are you sure?', :method => :delete, :id => "excluir-caso-#{caso.id.to_s}"

%br

=link_to t('direito.novocaso'), new_grupo_caso_path(@grupo)
\|
=link_to t('Back'), grupo_path(@grupo)

app/views/casos/new.html.haml
%h1 New caso

= render 'form'

= link_to t('Back'), grupo_casos_path(@grupo)

app/views/casos/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @caso.nome
%p
  %b Assunto:
  = @caso.assunto
%p
  %b Descricao:
  = @caso.descricao

= link_to t('Edit'), edit_grupo_caso_path(@grupo, @caso)
\|
= link_to t('Back'), grupo_casos_path(@grupo)