config/routes.rb
Direito::Application.routes.draw do

  resources :simulacoes, :only => [:show] do 
    post 'upload_peticao', :on => :member
    post 'upload_provas', :on => :member
  end

  resources :grupos do
    get 'participar', :on => :member
    resources :turmas
    resources :casos
    resources :propostas
  end

  get 'grupos/:id/aprovar/:user_id',  to: 'grupos#aprovar',   as: 'aprovar_participacao'
  get 'grupos/:id/reprovar/:user_id', to: 'grupos#reprovar',  as: 'reprovar_participacao'

  devise_for :users

  root :to => 'grupos#index'

end

app/models/proposta.rb
class Proposta < ActiveRecord::Base
  mount_uploader :anexo, PropostaUploader
  resourcify
  attr_accessible :assunto, :descricao, :nome, :propositor, :anexo, :anexo_cache 
  belongs_to :grupo
  belongs_to :propositor, :class_name => "User"
  
  has_many :simulacoes
  
end

app/controllers/propostas_controller.rb
class PropostasController < ApplicationController
  # GET /propostas
  # GET /propostas.json
  def index
    @grupo = Grupo.find(params[:grupo_id])
    @propostas = @grupo.propostas

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @propostas }
    end
  end

  # GET /propostas/1
  # GET /propostas/1.json
  def show
    @grupo = Grupo.find(params[:grupo_id])
    @proposta = Proposta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proposta }
    end
  end

  # GET /propostas/new
  # GET /propostas/new.json
  def new
    @grupo = Grupo.find(params[:grupo_id])
    @proposta = @grupo.propostas.build
    

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proposta }
    end
  end

  # GET /propostas/1/edit
  def edit
    @grupo = Grupo.find(params[:grupo_id])
    @proposta = Proposta.find(params[:id])
  end

  # POST /propostas
  # POST /propostas.json
  def create
    @grupo = Grupo.find(params[:grupo_id])
    @proposta = @grupo.propostas.build(params[:proposta])
    @proposta.propositor = current_user
    
    
    respond_to do |format|
      if @proposta.save
        format.html { redirect_to [@grupo, @proposta], notice: 'Proposta was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /propostas/1
  # PUT /propostas/1.json
  def update
    @grupo = Grupo.find(params[:grupo_id])
    @proposta = Proposta.find(params[:id])

    respond_to do |format|
      if @proposta.update_attributes(params[:proposta])
        format.html { redirect_to [@grupo, @proposta], notice: 'Proposta was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /propostas/1
  # DELETE /propostas/1.json
  def destroy
    @grupo = Grupo.find(params[:grupo_id])
    @proposta = Proposta.find(params[:id])
    authorize! :destroy, @proposta
    
    @proposta.destroy

    respond_to do |format|
      format.html { redirect_to grupo_propostas_path(@grupo) }
    end
  end
end

app/helpers/propostas_helper.rb
module PropostasHelper
end

app/views/propostas/_form.html.haml
= form_for ([@grupo, @proposta]) do |f|
  -if @proposta.errors.any?
    #error_explanation
      %h2= "#{pluralize(@proposta.errors.count, "error")} prohibited this proposta from being saved:"
      %ul
        - @proposta.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nome
    = f.text_field :nome
  .field
    = f.label :assunto
    = f.text_field :assunto
  .field
    = f.label :descricao
    = f.text_area :descricao
  .field
    = f.label :anexo
    = f.file_field :anexo
    = f.hidden_field :anexo_cache
    
    
  .actions
    = f.submit t('Save'), :id => "Save"

app/views/propostas/edit.html.haml
%h1 Editing proposta

= render 'form'


= link_to t('Show'), grupo_proposta_path(@grupo, @proposta)
\|
= link_to t('Back'), grupo_propostas_path(@grupo)

app/views/propostas/index.html.haml
%h1 Listing propostas

%table
  %tr
    %th Nome
    %th Assunto
    %th
    %th

  - @propostas.each do |proposta|
    %tr
      %td= link_to proposta.nome, grupo_proposta_path(@grupo, proposta)
      %td= proposta.assunto
      %td= link_to_if (can? :update, proposta), t('Edit'), edit_grupo_proposta_path(@grupo, proposta), id: "editar-proposta-#{proposta.id.to_s}"
      %td= link_to_if (can? :destroy, proposta), t('Destroy'), grupo_proposta_path(@grupo, proposta), :confirm => 'Are you sure?', :method => :delete, :id => "excluir-proposta-#{proposta.id.to_s}"

%br

= link_to 'Nova proposta de Caso', new_grupo_proposta_path(@grupo)
\|
= link_to t('Back'), grupo_path(@grupo)

app/views/propostas/new.html.haml
%h1 Nova proposta

= render 'form'

= link_to t('Back'), grupo_propostas_path(@grupo)

app/views/propostas/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @proposta.nome
%p
  %b Assunto:
  = @proposta.assunto
%p
  %b Descricao:
  = @proposta.descricao

%p#propositor
  %b Propositor:
  = image_tag lavatar_url(@proposta.propositor), :alt =>@proposta.propositor.email 
  = @proposta.propositor.email

%p
  %b Anexo:
  = link_to image_tag('baixar-documento.png'), @proposta.anexo.url, :id=>'anexo'


= link_to t('Edit'), edit_grupo_proposta_path(@grupo, @proposta)
\|
= link_to t('Back'), grupo_propostas_path(@grupo)